# Generated by Django 2.1.7 on 2024-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240319_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default=1, max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='tb_users',
        ),
    ]
